main: decision_tree/src/Tree.java decision_tree/src/Learner.java
	javac decision_tree/src/*.java

run: decision_tree/src/Learner.class
	java decision_tree.Learner

.Phony: clean
clean:
	rm -f decision_tree/src/*.class